name: ButtonTP
main: org.drastan.ButtonTP.ButtonTp
api-version: 1.13
version: 2.0.0-SNAPSHOT
author: Sega0795
website: www.drastan.net
description: Teleport using buttons with price/reward/custom messages
depend: [Vault]
startup: postworld
commands:
  btp:
    description: Used to setup and manage Warps
    usage: /<command> help
    aliases: [buttontp]
permissions:
  buttontp.use:
    description: Needed to activate a Warp
    default: true
  buttontp.commandwarp:
    description: Needed to Warp by command
  buttontp.getreward:
    description: Needed to receive money from a Warp
    default: true
  buttontp.freewarp:
    description: Use any Warp free of charge
  buttontp.make:
    description: Needed to create a Warp (/bw make)
  buttontp.move:
    description: Needed to move the destination of a Warp (/bw move)
  buttontp.link:
    description: Needed to link a Block to a Warp (/bw link)
  buttontp.unlink:
    description: Needed to unlink a Block to a Warp (/bw unlink)
  buttontp.delete:
    description: Needed to delete a Warp (/bw delete)
  buttontp.cost:
    description: Needed to set the amount of money taken when using a Warp (/bw cost)
  buttontp.reward:
    description: Needed to set the amount of money given when using a Warp (/bw reward)
  buttontp.access:
    description: Needed to set who has access to a Warp (/bw access)
  buttontp.source:
    description: Needed to set the source of money given/taken when using a Warp (/bw source)
  buttontp.cmd:
    description: Needed to add or remove commands to a Warp (/bw cmd)
  buttontp.msg:
    description: Needed to set the msg sent by a Warp (/bw msg)
  buttontp.time:
    description: Needed to set the reset time of a Warp (/bw time)
  buttontp.type:
    description: Needed to set the reset type of a Warp (/bw type)
  buttontp.max:
    description: Needed to set the maximum uses of a Warp Button (/bw max)
  buttontp.allow:
    description: Needed to set that items can be taken while warping (/bw allow)
  buttontp.deny:
    description: Needed to set that items cannt be taken while warping (/bw deny)
  buttontp.reset:
    description: Needed to reset activation times of a Warp (/bw reset)
  buttontp.list:
    description: Needed to list all Warps (/bw list)
  buttontp.find:
    description: Needed to search in list of warps (/bw find)
  buttontp.info:
    description: Needed to list information about a Warp (/bw info)
  buttonwarp.rl:
    description: Needed to reload the plugin (/bw rl)
  buttontp.create:
    description: Groups all Warp creation/setup nodes
    children:
      buttontp.make: true
      buttontp.list: true
      buttontp.info: true
      buttontp.link: true
      buttontp.unlink: true
      buttontp.delete: true
      buttontp.cost: true
      buttontp.reward: true
      buttontp.access: true
      buttontp.source: true
      buttontp.cmd: true
      buttontp.msg: true
      buttontp.time: true
      buttontp.type: true
      buttontp.max: true
      buttontp.allow: true
      buttontp.deny: true
  buttontp.admin:
    description: Needed to break linked Blocks